import { Any, KeyOf, List } from "@mantlebee/ts-core";

import { CountsMap, Dataset, Row, TableKey } from "./types";

/**
 * Represents the column of a table ({@link ITable}).
 * Its purpose is to generate a value for the row generated by the table.
 * @typeParam TRow - Type of the row.
 * @typeParam TValue - Type of the column's value.
 */
export interface IColumn<TRow extends Row, TValue = Any> {
  /**
   * Column's name. It must be unique for a {@link ITable}.
   */
  readonly name: KeyOf<TRow>;
  /**
   * Generates a value. The returned value is applied to the row.
   * @param row Row to update. The row has the values of the previous columns already processed.
   */
  getValue(row: TRow): TValue;
}

/**
 * Represents the column of a table ({@link ITable}), used to generate data based on values of rows from a different table.
 * Its purpose is to generate a default value for the row generated by the table, and to update it when target table's rows are generated.
 * @typeParam TRow - Type of the row.
 * @typeParam TTargetRow - Type of the row of the related table.
 * @typeParam TValue - Type of the column's value.
 */
export interface IColumnRelation<
  TRow extends Row,
  TTargetRow extends Row,
  TValue = Any,
> extends IColumn<TRow, TValue> {
  /**
   * Update source table rows using a target table rows or the entire dataset.
   * @param sourceRows List of rows to update of the source table.
   * @param targetRows List of rows of the target table.
   * @param dataset The entire database dataset.
   */
  setValues(
    sourceRows: List<TRow>,
    targetRows: List<TTargetRow>,
    dataset: Dataset
  ): void;
}

/**
 * Represents a database with its own tables ({@link ITable}) and relations {@link Relation}.
 * Its purpose is to generate the database dataset.
 * The {@link Dataset} object is a dictionary, where the keys are the tables names and the values are the generated rows.
 */
export interface IDatabase {
  /**
   * List of tables that must be used to generate rows.
   */
  readonly tables: List<ITable<Any>>;
  /**
   * Generates the database dataset, it is a dictionary, where the keys are the tables names and the values are the generated rows.
   * @param countsMap Dictionary with the tables counts, used to generate a specific amount of rows for each table. It is a dictionary where the keys are the tables names and the values the row counts to generate.
   */
  getDataset(countsMap: CountsMap): Dataset;
}

/**
 * Represents a table.
 * Its purpose is to generate rows.
 * @typeParam TRow - Type of the row.
 */
export interface ITable<TRow extends Row> {
  /**
   * Return the table's columns used to generate values for the rows.
   */
  getColumns(): List<IColumn<TRow>>;
  /**
   * Return the table's key.
   */
  getKey(): TableKey<TRow>;
  /**
   * Returns the tables rows.
   * Returns an empty list, if {@link seed} hasn't be called, first.
   */
  getRows(): List<TRow>;
  /**
   * Generates a specific amount of rows.
   * @param rowsCount Number of rows to generate.
   */
  seed(rowsCount: number): ITable<TRow>;
}
